version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo

    environment:
      - MONGO_URI=${DB_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo

