version : "3"
service :
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo

    environment:
      - MONGO_URI=mongodb+srv://devp_sriram:kXoTP83RTF0qaeyt@crud-app.ko0xt.mongodb.net/?retryWrites=true&w=majority&appName=crud-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
  mongo:
    image:mongo
    volumes:
      - mongo_data:/data/db

